# Generated by Django 6.0 on 2025-12-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_contact',
            field=models.CharField(blank=True, help_text='Mobile or Email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='investor_split_percent',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='Percentage kept by Investor', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner_split_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Percentage going to Business Owner', max_digits=5),
        ),
    ]
