# Generated by Django 6.0 on 2025-12-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_contact',
            field=models.CharField(blank=True, help_text='Mobile or Email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
