# Generated by Django 6.0 on 2025-12-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sale_customer_contact_sale_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
