# Generated by Django 6.0 on 2025-12-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productchangerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productchangerequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='productchangerequest',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productchangerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
